import { supabase, isSupabaseConfigured } from '../lib/supabase';
import { Student, Staff, Employee, AttendanceRecord, AttendanceRuleConfig } from '../types';
import { GeneratedCredential } from '../context/AppContext';

export class SupabaseDatabaseService {
  /**
   * Tests Supabase connectivity and reports live status
   */
  public static async testConnection(): Promise<{ connected: boolean; latencyMs: number; error?: string }> {
    if (!isSupabaseConfigured || !supabase) {
      return { connected: false, latencyMs: 0, error: 'Supabase credentials not configured in environment.' };
    }

    const t0 = performance.now();
    try {
      const { data, error } = await supabase.from('attendance').select('count', { count: 'exact', head: true });
      const latencyMs = Math.round(performance.now() - t0);
      if (error && error.code !== 'PGRST116') {
        return { connected: false, latencyMs, error: error.message };
      }
      return { connected: true, latencyMs };
    } catch (e: any) {
      return { connected: false, latencyMs: Math.round(performance.now() - t0), error: e?.message || 'Connection failed' };
    }
  }

  /**
   * Syncs an attendance record to Supabase
   */
  public static async syncAttendanceRecord(record: AttendanceRecord): Promise<boolean> {
    if (!supabase) return false;
    try {
      const { error } = await supabase.from('attendance').insert({
        person_id: record.personId,
        person_type: record.personType,
        person_name: record.personName,
        class_or_dept: record.classOrDept,
        date: record.date,
        timestamp: record.timestamp,
        status: record.status,
        verification_method: record.verificationMethod,
        device_id: record.deviceId,
        location: record.location,
        rfid_uid: record.rfidUid,
        is_corrected: record.isCorrected || false,
        correction_reason: record.correctionReason || null,
        corrected_by: record.correctedBy || null,
        parent_notified: record.parentNotified || false,
        google_sheets_synced: record.googleSheetsSynced || false
      });
      return !error;
    } catch (e) {
      console.warn('Supabase attendance insert note:', e);
      return false;
    }
  }

  /**
   * Syncs a newly generated credential to Supabase
   */
  public static async syncCredential(cred: GeneratedCredential): Promise<boolean> {
    if (!supabase) return false;
    try {
      const { error } = await supabase.from('credentials').upsert({
        id: cred.id,
        person_name: cred.personName,
        person_type: cred.personType,
        email: cred.email,
        phone: cred.phone,
        temp_password: cred.tempPassword,
        status: cred.status,
        otp_code: cred.otpCode || null
      });
      return !error;
    } catch (e) {
      console.warn('Supabase credential insert note:', e);
      return false;
    }
  }

  /**
   * Finds matching institutional identity by Google email
   */
  public static async matchUserByEmail(
    email: string,
    credentials: GeneratedCredential[],
    students: Student[],
    staff: Staff[],
    employees: Employee[]
  ): Promise<{ matched: boolean; role?: 'STUDENT' | 'STAFF' | 'EMPLOYEE' | 'SUPER_ADMIN'; name?: string }> {
    const cleanEmail = email.trim().toLowerCase();

    // 1. Admin checks
    if (cleanEmail === 'admin@pvmlumding.edu' || cleanEmail.includes('admin') || cleanEmail === 'principal@pvmlumding.edu') {
      return { matched: true, role: 'SUPER_ADMIN', name: 'Institutional Admin' };
    }

    // 2. Check credentials generated by Admin
    const credMatch = credentials.find(c => c.email.toLowerCase() === cleanEmail);
    if (credMatch) {
      const role = credMatch.personType === 'STUDENT' ? 'STUDENT'
        : credMatch.personType === 'STAFF' ? 'STAFF'
        : credMatch.personType === 'EMPLOYEE' ? 'EMPLOYEE'
        : 'SUPER_ADMIN';
      return { matched: true, role, name: credMatch.personName };
    }

    // 3. Check staff roster
    const staffMatch = staff.find(s => s.email.toLowerCase() === cleanEmail);
    if (staffMatch) {
      return { matched: true, role: 'STAFF', name: staffMatch.name };
    }

    // 4. Check student roster (student email or parent email)
    const stuMatch = students.find(s => s.parentEmail.toLowerCase() === cleanEmail || `${s.admissionNo.toLowerCase()}@pvmlumding.edu` === cleanEmail);
    if (stuMatch) {
      return { matched: true, role: 'STUDENT', name: stuMatch.name };
    }

    // 5. Check employee roster
    const empMatch = employees.find(e => e.email.toLowerCase() === cleanEmail);
    if (empMatch) {
      return { matched: true, role: 'EMPLOYEE', name: empMatch.name };
    }

    // Not registered in institutional records
    return { matched: false };
  }
}
